### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [mlutfy/ca.bidon.reporterror#16]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by mlutfy** [comment]
To my knowledge, there should not be any big change that affects the extension. I haven't tested yet, but have been playing with 4.6 a bit, and do not foresee big issues. I'll wait until civicrm.org creates the 4.6 tag for extensions, otherwise the info.xml gets rejected by the auto-release scripts.

**Comment by mlutfy** [comment]
Closing this issue, since the extension seems to work well on 4.6.

PS: I released a new version 2.8 today, which adds some features to better handle bots/crawlers.
